### ISSUE TITLE
Dataset link is empty

### ISSUE THREAD

**Issue by tom2330** [facebookresearch/SSLForPDEs#1]
[https://microsoft.github.io/pdearena/datadownload/#conditioning-dataset]When I open it, it's empty. There's no data. How do I fix it?

**Comment by garridoq** [comment]
Hi, the website seems to be down. The last instructions on the website pointed to the following link, which still seems to work:

https://huggingface.co/datasets/pdearena/NavierStokes-2D-conditoned

We'll update the readme accordingly if the website doesn't come back up. Thanks for raising this issue !

**Comment by garridoq** [comment]
We've updated the README with the aforementioned link since the original website is still not up.
